"""Removing username from influencers

Revision ID: 8ef19dc92a93
Revises: 75784f2e4d8b
Create Date: 2025-06-12 15:19:49.160218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef19dc92a93'
down_revision: Union[str, None] = '75784f2e4d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('influencers_username_key'), 'influencers', type_='unique')
    op.drop_column('influencers', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencers', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('influencers_username_key'), 'influencers', ['username'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
